### ISSUE TITLE
Crashes when using Tilecache

### ISSUE THREAD

**Issue by PothpothBR** [mapsforge/vtm#1077]
I have a simple demo that reproduces the error, it seems that when enabling the tile cache a nullpointer occurs.

```java
        map = binding.mapView.map();
        mapPreferences = new MapPreferences(MainActivity.class.getName(), this);

        BitmapTileSource tileSource = DefaultSources.OPENSTREETMAP.build();

        MapRenderer.setBackgroundColor(0xff667777);

        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        tileSource.setHttpEngine(new OkHttpEngine.OkHttpFactory(builder));

        boolean reproduceError = true;

        if (reproduceError) {
            TileCache cache = new TileCache(this, null, "mapcache.temp");
            cache.setCacheSize(512 * (1 << 10));
            tileSource.setCache(cache);
        }

        BitmapTileLayer tileLayer = new BitmapTileLayer(map, tileSource);
        map.layers().add(tileLayer);
```

This is the error:
```stacktrace
FATAL EXCEPTION: main
Process: com.example.vtmmapdemo, PID: 22163
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.oscim.layers.tile.MapTile.state()' on a null object reference
    at org.oscim.layers.tile.TileManager$JobCompletedEvent.run(TileManager.java:651)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7872)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by devemux86** [comment]
(TileSource.setCache is the old method)

See the [BitmapTileActivity](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/src/org/oscim/android/test/BitmapTileActivity.java) for how to use a cache (via OkHttp) with online tile sources.

**Comment by PothpothBR** [comment]
Thanks, it works fine for me!
