### ISSUE TITLE
NPE with destroy Map if TileSource are NULL

### ISSUE THREAD

**Issue by Longri** [mapsforge/vtm#175]
09-21 08:51:12.973 13033-13730/de.longri.cachebox3 E/AndroidRuntime: FATAL EXCEPTION: GLThread 9838
                                                                     Process: de.longri.cachebox3, PID: 13033
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void org.oscim.tiling.TileSource.close()' on a null object reference
                                                                         at org.oscim.layers.tile.vector.VectorTileLayer.onDetach(VectorTileLayer.java:178)
                                                                         at org.oscim.map.Layers.destroy(Layers.java:196)
                                                                         at org.oscim.map.Map.destroy(Map.java:209)

Better is a check off NULL in VectorTileLayer.jave Line 178

```
 @Override
    public void onDetach() {
        super.onDetach();
      if(mTileSource!=null)  mTileSource.close();
    }
```

**Comment by devemux86** [comment]
Nice catch, do you want to post a PR?

**Comment by Longri** [comment]
Not realy, to match effort for only 22 characters! ;-)

Without copyright, which I renounce!

I will help to find Exceptions!

**Comment by devemux86** [comment]
I pushed the fix by you.
You should keep a VTM clone handy for such cases. :smile:
