### ISSUE TITLE
Number Format Exception for building height

### ISSUE THREAD

**Issue by boldtrn** [mapsforge/vtm#271]
I just received a `java.lang.NumberFormatException: For input string: "23.0"`

Stacktrace:
```
java.lang.NumberFormatException: For input string: "23.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.oscim.layers.tile.buildings.BuildingLayer.process(BuildingLayer.java:84)
	at org.oscim.layers.tile.vector.VectorTileLayer.callThemeHooks(VectorTileLayer.java:189)
	at org.oscim.layers.tile.vector.VectorTileLoader.renderExtrusion(VectorTileLoader.java:329)
	at org.oscim.theme.styles.ExtrusionStyle.renderWay(ExtrusionStyle.java:91)
	at org.oscim.layers.tile.vector.VectorTileLoader.renderWay(VectorTileLoader.java:224)
	at org.oscim.layers.tile.vector.VectorTileLoader.process(VectorTileLoader.java:214)
	at org.oscim.tiling.source.mvt.TileDecoder.decodeLayer(TileDecoder.java:247)
	at org.oscim.tiling.source.mvt.TileDecoder.decode(TileDecoder.java:95)
	at org.oscim.tiling.source.UrlTileDataSource.query(UrlTileDataSource.java:86)
	at org.oscim.layers.tile.vector.VectorTileLoader.loadTile(VectorTileLoader.java:136)
	at org.oscim.layers.tile.TileLoader.doWork(TileLoader.java:66)
	at org.oscim.utils.PausableThread.run(PausableThread.java:141)

```

**Comment by devemux86** [comment]
It's from Mapzen `.mvt` tiles, right?
Thanks for reporting this @boldtrn !

**Comment by boldtrn** [comment]
@devemux86, yes exactly. They seem to return coma values for the height.
