### ISSUE TITLE
Crash on  Turkic locales

### ISSUE THREAD

**Issue by mpelesh** [mapsforge/vtm#297]
Steps to reproduce:

1. In custom locale change locale to Turkish
2. Select default theme.

Map crashes with with the exception:

> org.oscim.theme.IRenderTheme$ThemeException: BOLD_İTALİC is not a constant in org.oscim.backend.canvas.Paint$FontStyle
                                                             at org.oscim.theme.XmlThemeBuilder.read(XmlThemeBuilder.java:109)
                                                             at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:46)
                                                             at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:42)
                                                             at org.oscim.map.Map.setTheme(Map.java:203)
                                                             at org.oscim.map.Map.setTheme(Map.java:195)

Caused by `value.toUpperCase()` call in `XmlThemeBuilder`, line 900. In Turkic languages lower case "i" is converted to "İ" not to "I".

The solution would be to have upper-case "ITALIC" and "BOLD_ITALIC" style values in theme XML files. In this case `value.toUpperCase()` call will not depend on locale.

**Comment by devemux86** [comment]
Thanks for the report, we need to fix it before `0.7.0` release!

A simpler solution, since theme enums have English values, is using `toUpperCase(Locale.ENGLISH)` in those string case changes.

**Comment by devemux86** [comment]
I pushed the fix, could you check too?

**Comment by devemux86** [comment]
Oh you intended to post a pull request?
Sorry about not waiting.. :slightly_smiling_face:

**Comment by mpelesh** [comment]
Yes,  I have create a pull request https://github.com/mapsforge/vtm/pull/298

**Comment by devemux86** [comment]
Unfortunately I had already pushed the fix, see 967875d6b8c17c4833053976aeb0eb97fc6d87d7.

**Comment by mpelesh** [comment]
> Unfortunately I had already pushed the fix, see 967875d.

Not a problem. The issue is closed and this is the only thing that counts :)

**Comment by devemux86** [comment]
Thanks and waiting for more contributions!
