### ISSUE TITLE
Mapsforge: empty tiles

### ISSUE THREAD

**Issue by devemux86** [mapsforge/vtm#371]
Trying this sample map [dienten_V4.zip](https://github.com/mapsforge/vtm/files/1116309/dienten_V4.zip) we have empty tiles with exceptions:

```java
java.lang.ArrayIndexOutOfBoundsException: 25543
	at org.oscim.tiling.source.mapfile.ReadBuffer.readSignedInt(ReadBuffer.java:216)
	at org.oscim.tiling.source.mapfile.MapDatabase.decodeWayNodes(MapDatabase.java:644)
	at org.oscim.tiling.source.mapfile.MapDatabase.processWayDataBlock(MapDatabase.java:635)
	at org.oscim.tiling.source.mapfile.MapDatabase.processWays(MapDatabase.java:865)
	at org.oscim.tiling.source.mapfile.MapDatabase.processBlock(MapDatabase.java:358)
	at org.oscim.tiling.source.mapfile.MapDatabase.processBlocks(MapDatabase.java:507)
	at org.oscim.tiling.source.mapfile.MapDatabase.query(MapDatabase.java:261)
	at org.oscim.layers.tile.vector.VectorTileLoader.loadTile(VectorTileLoader.java:136)
	at org.oscim.layers.tile.TileLoader.doWork(TileLoader.java:66)
	at org.oscim.utils.PausableThread.run(PausableThread.java:141)
```

**Comment by devemux86** [comment]
Discussion in [forum](https://groups.google.com/forum/#!topic/mapsforge-dev/kQKfCMGk2Ec).

**Comment by devemux86** [comment]
Will be addressed in map-writer side (see https://github.com/mapsforge/mapsforge/issues/971) to produce valid map files.
