### ISSUE TITLE
Failed Error when load map in ios app

### ISSUE THREAD

**Issue by firdauskz01** [mapsforge/vtm#531]
Hi, I'm new on vtm and also native app.
Please help me with this Error? 
```

java.lang.ExceptionInInitializerError
	at org.oscim.ios.backend.IosSvgBitmap.getResourceBitmap(IosSvgBitmap.java:60)
	at org.oscim.ios.backend.IosSvgBitmap.getResourceBitmapImpl(IosSvgBitmap.java:93)
	at org.oscim.ios.backend.IosSvgBitmap.<init>(IosSvgBitmap.java:97)
	at org.oscim.ios.backend.IosGraphics.decodeSvgBitmapImpl(IosGraphics.java:64)
	at org.oscim.backend.CanvasAdapter.decodeSvgBitmap(CanvasAdapter.java:129)
	at org.oscim.backend.CanvasAdapter.createBitmap(CanvasAdapter.java:176)
	at org.oscim.ios.backend.IosGraphics.loadBitmapAssetImpl(IosGraphics.java:69)
	at org.oscim.backend.CanvasAdapter.getBitmapAsset(CanvasAdapter.java:146)
	at org.oscim.theme.XmlThemeBuilder.createSymbol(XmlThemeBuilder.java:1112)
	at org.oscim.theme.XmlThemeBuilder.startElement(XmlThemeBuilder.java:287)
	at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143)
	at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method)
	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513)
	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
	at org.oscim.backend.XMLReaderAdapter.parse(XMLReaderAdapter.java:42)
	at org.oscim.theme.XmlThemeBuilder.read(XmlThemeBuilder.java:110)
	at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:53)
	at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:45)
	at com.ramani.ujuizi.maps.MapAppiOS.createLayers(MapAppiOS.java:69)
	at org.oscim.gdx.GdxMap.create(GdxMap.java:98)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics.draw(IOSGraphics.java:316)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.draw(IOSGraphics.java:212)
	at com.badlogic.gdx.backends.iosrobovm.IOSGraphics$1.$cb$drawRect$(IOSGraphics.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:428)
	at com.ramani.ujuizi.maps.IOSLauncher.main(IOSLauncher.java:48)
Caused by: org.robovm.objc.ObjCClassNotFoundException: SVGParser
	at org.robovm.objc.ObjCClass.getByType(ObjCClass.java:258)
	at svg.SVGParser.<clinit>(SVGParser.java:20)
	... 28 more

```
and this is my code 
  ```
@Override
        public void createLayers() {
            Map map = getMap();

            VectorTileLayer l = map.setBaseMap(new OSciMap4TileSource());

            GroupLayer groupLayer = new GroupLayer(mMap);
            groupLayer.layers.add(new BuildingLayer(map, l));
            groupLayer.layers.add(new LabelLayer(map, l));
            map.layers().add(groupLayer);

            DefaultMapScaleBar mapScaleBar = new DefaultMapScaleBar(mMap);
            mapScaleBar.setScaleBarMode(DefaultMapScaleBar.ScaleBarMode.BOTH);
            mapScaleBar.setDistanceUnitAdapter(MetricUnitAdapter.INSTANCE);
            mapScaleBar.setSecondaryDistanceUnitAdapter(ImperialUnitAdapter.INSTANCE);
            mapScaleBar.setScaleBarPosition(MapScaleBar.ScaleBarPosition.BOTTOM_LEFT);

            MapScaleBarLayer mapScaleBarLayer = new MapScaleBarLayer(mMap, mapScaleBar);
            BitmapRenderer renderer = mapScaleBarLayer.getRenderer();
            renderer.setPosition(GLViewport.Position.BOTTOM_LEFT);
            renderer.setOffset(5, 0);
            map.layers().add(mapScaleBarLayer);

            map.setTheme(VtmThemes.DEFAULT);
            map.setMapPosition(53.075, 8.808, 1 << 17);
        }
```

this error happened when loaded   `map.setTheme(ThemeLoader.load(VtmThemes.DEFAULT), true);`

**Comment by firdauskz01** [comment]
@devemux86 I think yes it is, but I already added vtm-ios inside dependency
here is my dependendy 

```
dependencies {
    compile "org.mapsforge:vtm-ios:0.9.2"
    natives "org.mapsforge:vtm-ios:0.9.2:natives"

    compile 'com.vividsolutions:jts:1.13'
//    compile 'com.caverock:androidsvg:1.2.2-beta-1'
    compile "org.mapsforge:vtm:0.9.2"
    compile "org.mapsforge:vtm-jts:0.9.2"
    compile "org.mapsforge:vtm-gdx:0.9.2"
    compile "org.slf4j:slf4j-simple:1.7.25"


    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-ios"
    implementation "com.badlogicgames.gdx:gdx-backend-robovm:$gdxVersion"
    implementation "com.mobidevelop.robovm:robovm-rt:$roboVMVersion"
    implementation "com.mobidevelop.robovm:robovm-cocoatouch:$roboVMVersion"
}

```

**Comment by Longri** [comment]
show me your robovm.xml

I thing you must register the SVGH lib like:


```
.......
     <libs>
        <lib>z</lib>
        <lib>build/native/libvtm-jni.a</lib>  <!--vtm native -->
        <lib>libs/libLibPP.a</lib>  <!--libPP native -->
        <lib>build/native/META-INF/robovm/ios/libs/libGdxSqlite.a</lib>  <!--GdxSqlite native -->
    </libs>
    <frameworkPaths>
        <path>build/native</path>  <!--SVGgh framework path -->
    </frameworkPaths>
    <frameworks>
        <framework>SVGgh</framework> <!--SVGgh framework name -->
        <framework>UIKit</framework>
        <framework>OpenGLES</framework>
        <framework>QuartzCore</framework>
        <framework>CoreGraphics</framework>
        <framework>OpenAL</framework>
        <framework>AudioToolbox</framework>
        <framework>AVFoundation</framework>
        <framework>CoreLocation</framework>
        <framework>WebKit</framework>
    </frameworks>
</config>
```

**Comment by firdauskz01** [comment]
I just follows this [instructions](https://github.com/mapsforge/vtm/blob/master/docs/ios.md).
So this is my robovm.xml    
`  
  <libs>
    <lib>z</lib>
    <lib>build/native/libvtm-jni.a</lib>  
  </libs>
  <frameworkPaths>
    <path>build/native</path>  
  </frameworkPaths>
  <frameworks>
    <framework>SVGgh</framework> 
    <framework>UIKit</framework>
    <framework>OpenGLES</framework>
    <framework>QuartzCore</framework>
    <framework>CoreGraphics</framework>
    <framework>OpenAL</framework>
    <framework>AudioToolbox</framework>
    <framework>AVFoundation</framework>
  </frameworks>
`

**Comment by Longri** [comment]
please can you check if SVgh.framework copied into build folder

![image](https://user-images.githubusercontent.com/2542295/39040858-354e06b0-4488-11e8-90ae-2623bae688ca.png)

**Comment by firdauskz01** [comment]
Yes there is SVGgh.framework there 
![build](https://user-images.githubusercontent.com/19215383/39041413-eaafcf5a-44b2-11e8-9d5a-c7d1050f0c26.jpeg)

**Comment by Longri** [comment]
can you try to compile SVGgh with your provisioning profile, with XCode?

Maybe it's because the version was compiled with my provisioning profile?

The Source can you find on:
https://github.com/GenerallyHelpfulSoftware/SVGgh

**Comment by firdauskz01** [comment]
Okay let me try it. Thanks @Longri

**Comment by firdauskz01** [comment]
Hi @Longri , I think the problem is from my IDE, but I'm still investigating this issue.
I tried with your suggested above is still get same error.
And then I compiled the Project via Terminal , but I got this 

`13:03:04.937 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 8478261248, Committed: 1096810496}`

**Comment by Longri** [comment]
Ok, then try IDEA 1017.2 with Gradle 2.3.0 and latest Snapshot-PlugIn from http://robovm.mobidevelop.com/downloads/snapshots/idea/

This is the combination that works for me with Xcode 9.3

**Comment by firdauskz01** [comment]
I already intall the those latest robovm SnapShot-Plugin, and I'm using xcode 8.3.
I will try to update the xcode first.

**Comment by firdauskz01** [comment]
Okay, after I updated macOS High Sierra 10.13.4 and also Xcode 9.3, now it's runing well on the simulator.
I think the main problem because I used the old macOS Sierra 10.12.X and Xcode 8.3.

**Comment by devemux86** [comment]
Nice to hear that!

If you think the [iOS instructions](https://github.com/mapsforge/vtm/blob/master/docs/ios.md) can be improved, so that users can use VTM on iOS more easily, please don't hesitate to propose changes or post a pull request. :slightly_smiling_face:

**Comment by Longri** [comment]
Last question. Which SVGgh version did you use? Our pre-compiled or a self-compiled?

**Comment by firdauskz01** [comment]
@Longri I just create a new project and then adding this dependencies in build.gradle file.
So, I did use  your pre-compiled SVGgh in my project.

```
dependency{
    ....
    compile "org.mapsforge:vtm-ios:0.9.2"
    natives "org.mapsforge:vtm-ios:0.9.2:natives"
    compile "org.mapsforge:vtm-jts:master-SNAPSHOT"
}
```
