### ISSUE TITLE
Crash on Android Pie

### ISSUE THREAD

**Issue by firdauskz01** [mapsforge/vtm#597]
Hi, I'm trying to Run on Android Pie, but I got crash on when render the map.
Here is the Error :
```java
  org.oscim.theme.IRenderTheme$ThemeException: Attempt to read from field 'int org.oscim.renderer.bucket.TextureItem.width' on a null object reference
        at org.oscim.theme.XmlThemeBuilder.read(XmlThemeBuilder.java:112)
        at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:53)
        at org.oscim.theme.ThemeLoader.load(ThemeLoader.java:45)
```

this is my setup map:

```java
  OSciMap4TileSource tileSource = new OSciMap4TileSource();

        mMapView.setMapPosition(new GeoPoint(51.221297, 4.399128), 7);
        TileCache mCache = new TileCache(this, null, "opensciencemap-tiles.db");
        mCache.setCacheSize(512 * (1 << 10));
        tileSource.setCache(mCache);

        VectorTileLayer mBaseLayer = mMap.setBaseMap(tileSource);
        mMap.layers().add(new BuildingLayer(mMap, mBaseLayer));
        mMap.layers().add(new LabelLayer(mMap, mBaseLayer));
        mMap.setTheme(ThemeLoader.load(VtmThemes.OSMARENDER), true);
```

Can you help me about this?

**Comment by firdauskz01** [comment]
Hi @devemux86 , I already success run on Android, but after I update Target SDK Version to 28, and build tools version to 28.0.0, this caused crash.

**Comment by devemux86** [comment]
Testing VTM samples on Android 9, they seem to work fine.

Probably need to debug your implementation and compare with the examples code, e.g. first initialize the map and them set its position.

**Comment by firdauskz01** [comment]
I got this crash when I set  gradle version classpath to `'com.android.tools.build:gradle:3.2.1'` in the root project, and    ` compileSdkVersion 28` and   `targetSdkVersion 28`,  build tools version  to  ` 28.0.0`.    
But, when I downgrade it all
gradle version classpath to `'com.android.tools.build:gradle:3.1.0+'` in the root project, and    ` compileSdkVersion 27` and   `targetSdkVersion 27`,  build tools version  to  ` 27.1.1`.
 it's working well

**Comment by devemux86** [comment]
See if need to use the `usesCleartextTraffic` attribute in manifest, like demonstrated in [vtm-android-example](https://github.com/mapsforge/vtm/blob/master/vtm-android-example/AndroidManifest.xml#L16).

OSciM tile source uses http and [Starting with Android 9 (API level 28), cleartext support is disabled by default](https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted).
