### ISSUE TITLE
crash in 0.18 VtmAsyncExecutor

### ISSUE THREAD

**Issue by Meibes** [mapsforge/vtm#974]
I just had a crash - any idea what could have caused it or what can be done to avoid it?

here is the log:
```
2022-11-16 14:32:35.579 12529-13830 System.err              xxx             W  java.lang.NullPointerException: Attempt to read from field 'short[] org.oscim.renderer.bucket.VertexData$Chunk.vertices' on a null object reference
2022-11-16 14:32:35.588 12529-13830 System.err              xxx             W  	at org.oscim.renderer.bucket.VertexData.getNext(VertexData.java:143)
2022-11-16 14:32:35.588 12529-13830 System.err              xxx             W  	at org.oscim.renderer.bucket.VertexData.add(VertexData.java:164)
2022-11-16 14:32:35.588 12529-13830 System.err              xxx             W  	at org.oscim.renderer.bucket.PolygonBucket.addPolygon(PolygonBucket.java:87)
2022-11-16 14:32:35.588 12529-13830 System.err              xxx             W  	at org.oscim.layers.tile.vector.VectorTileLoader.renderArea(VectorTileLoader.java:304)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.theme.styles.AreaStyle.renderWay(AreaStyle.java:138)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.layers.tile.vector.VectorTileLoader.renderWay(VectorTileLoader.java:208)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.layers.tile.vector.VectorTileLoader.process(VectorTileLoader.java:198)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.tiling.source.mapfile.MapDatabase.processWays(MapDatabase.java:1085)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.tiling.source.mapfile.MapDatabase.processBlock(MapDatabase.java:422)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.tiling.source.mapfile.MapDatabase.processBlocks(MapDatabase.java:610)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.tiling.source.mapfile.MapDatabase.processBlocks(MapDatabase.java:498)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.tiling.source.mapfile.MapDatabase.query(MapDatabase.java:315)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.tiling.OverzoomTileDataSource.query(OverzoomTileDataSource.java:42)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.layers.tile.vector.VectorTileLoader.loadTile(VectorTileLoader.java:120)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.layers.tile.TileLoader.doWork(TileLoader.java:66)
2022-11-16 14:32:35.589 12529-13830 System.err              xxx             W  	at org.oscim.utils.PausableThread.run(PausableThread.java:141)
2022-11-16 14:32:35.667 12529-12541 xxx                     xxx             I  Background concurrent copying GC freed 261223(12MB) AllocSpace objects, 303(6944KB) LOS objects, 29% free, 56MB/80MB, paused 2.528ms,120us total 140.581ms
2022-11-16 14:32:36.771 12529-13862 AndroidRuntime          xxx             E  FATAL EXCEPTION: VtmAsyncExecutor
                                                                                                    Process: xxx, PID: 12529
                                                                                                    java.lang.IllegalStateException
                                                                                                    	at org.oscim.utils.pool.Inlist$List.next(Inlist.java:139)
                                                                                                    	at org.oscim.utils.pool.Inlist$List.next(Inlist.java:33)
                                                                                                    	at org.oscim.layers.tile.vector.labeling.LabelPlacement.addWayLabels(LabelPlacement.java:207)
                                                                                                    	at org.oscim.layers.tile.vector.labeling.LabelPlacement.updateLabels(LabelPlacement.java:461)
                                                                                                    	at org.oscim.layers.tile.vector.labeling.LabelLayer$Worker.doWork(LabelLayer.java:83)
                                                                                                    	at org.oscim.layers.tile.vector.labeling.LabelLayer$Worker.doWork(LabelLayer.java:74)
                                                                                                    	at org.oscim.utils.async.SimpleWorker.run(SimpleWorker.java:73)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
```

**Comment by Meibes** [comment]
it probably is a problem with my own implementation, but I don't have time to check it right now, this time the crash is slightly different:

`FATAL EXCEPTION: VtmAsyncExecutor
    Process: xxx, PID: 8427
    java.lang.IllegalStateException
    	at org.oscim.utils.pool.Inlist$List.next(Inlist.java:139)
    	at org.oscim.utils.pool.Inlist$List.next(Inlist.java:33)
    	at org.oscim.layers.tile.vector.labeling.LabelPlacement.addNodeLabels(LabelPlacement.java:265)
    	at org.oscim.layers.tile.vector.labeling.LabelPlacement.updateLabels(LabelPlacement.java:474)
    	at org.oscim.layers.tile.vector.labeling.LabelLayer$Worker.doWork(LabelLayer.java:83)
    	at org.oscim.layers.tile.vector.labeling.LabelLayer$Worker.doWork(LabelLayer.java:74)
    	at org.oscim.utils.async.SimpleWorker.run(SimpleWorker.java:73)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
    	at java.lang.Thread.run(Thread.java:1012)`

**Comment by Meibes** [comment]
checking the logs further I also stumbled upon

```
2022-11-17 16:28:36.404  8427-8437  xxx                     xxx             I  Background young concurrent copying GC freed 67211(4286KB) AllocSpace objects, 118(2356KB) LOS objects, 4% free, 32MB/34MB, paused 1.009ms,129us total 121.152ms
2022-11-17 16:28:36.522  8427-8724  MapDatabase             xxx             E  [TileLoader98] null 
```

the problem seems to appear after GC starts, but the main cause is in my implementation, I moved around some things and didn't test properly.

a try/catch might be good

**Comment by devemux86** [comment]
`Inlist` has several `throws`.
Are all necessary or methods can exit early without crashing the library / apps?

Need good testing to not break the library.
e.g. in [Inlist.next](https://github.com/mapsforge/vtm/blob/master/vtm/src/org/oscim/utils/pool/Inlist.java#L139) what should return without an exception?

**Comment by Meibes** [comment]
the problem in my case was that I had MapFileTileSource as a global variable and while moving code I didn't notice I was reassigning the MapFileTileSource while the map was being drawn. This resulted in TileLoader logging dozens of errors and after some time the IllegalStateException from the LabelLayer. So the VectorTileLayer/TileLoader logs errors while the LabelLayer throws Exceptions which lead to the crash. here are some suggestions:

- add a description to the error e.g. change [IllegalStateException](https://github.com/mapsforge/vtm/blob/e1191f68ae3f8f591d0205e216d0f39f43e2fea5/vtm/src/org/oscim/utils/pool/Inlist.java#L139) to `IllegalArgumentException("'item' is null")`
- surround both [nodelabels ](https://github.com/mapsforge/vtm/blob/d29fd500e5c507326606d3e2418b35662ebfac87/vtm/src/org/oscim/layers/tile/vector/labeling/LabelPlacement.java#L265-L305) and [waylabels](https://github.com/mapsforge/vtm/blob/d29fd500e5c507326606d3e2418b35662ebfac87/vtm/src/org/oscim/layers/tile/vector/labeling/LabelPlacement.java#L207-L253) with try/catch and log the error

I don't know what "cur" stands for, so "item" might not be the best description
